function [fitresult, gof] = createFit_PowerLaw_TimeConstantVersion(SR, AppVis, mu0)
%CREATEFIT(SR,APPVIS)
%  Create a fit.
%
%  Data for 'Power-Law - Apparent Viscosity - Time constant version' fit:
%      X Input : SR
%      Y Output: AppVis
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Apr-2017 14:50:50


%% Fit: 'Power-Law - Apparent Viscosity - Time constant version'.
[xData, yData] = prepareCurveData( SR, AppVis );

% Set up fittype and options.
ft = fittype( 'mu0*(lambda*x)^(n-1)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 mu0 0];
opts.StartPoint = [0.1 mu0 0.7];
opts.Upper = [10000 mu0 1];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Power-Law - Apparent Viscosity - Time constant version' );
h = plot( fitresult, xData, yData );
legend( h, 'AppVis vs. SR', 'Power-Law - Apparent Viscosity - Time constant version', 'Location', 'NorthEast' );
% Label axes
xlabel SR
ylabel AppVis
grid on
set(gca,...
    'XScale','log',...
    'YScale','log');



