function [iteration, quantity] = importMonitoredQuantities(fullpath, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [ITERATION,MASSFLOWRATE] = IMPORTFILE(FILENAME) Reads data from text
%   file FILENAME for the default selection.
%
%   [ITERATION,MASSFLOWRATE] = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads
%   data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   [Iteration,MassFlowRate] = importfile('p_h2o-scaled_dpdx=0.001_mass-flow-rate.txt',3, 5003);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/05/18 09:43:58

%% Initialize variables.
delimiter = ' ';
if nargin<=2
    startRow = 3;
    endRow = inf;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(fullpath,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
iteration = dataArray{:, 1};
quantity = dataArray{:, 2};
% plot(Iteration,MassFlowRate);
% quantity = -quantity(end);



