% Create table of experimental Flow Loop data and derived variables


%% Read data and create tables

% List of worksheets
sheetlist = {'Single Water Flow - DP',...
    'Single PAC Flow - DP'};

% List of ranges in respective worksheets
rangelist = {'E97:M156',...
    'F2:P132'};

% Import data  & create table
Exp_H2O = readtable([path2 '\' filename_FlowLoopData],...
    'Sheet',sheetlist{1},...
    'Range',rangelist{1},...
    'ReadVariableNames',false);

Exp_PAC = readtable([path2 '\' filename_FlowLoopData],...
    'Sheet',sheetlist{2},...
    'Range',rangelist{2},...
    'ReadVariableNames',false);


%% Clean up, reorder and merge tables

% Rename and add data
Exp_H2O{:,3} = {'H2O'}; % Add fluid name
Exp_H2O{:,8} = Exp_H2O{:,8}.*100; % Convert to Pa/m
Exp_H2O{:,9} = Exp_H2O{:,9}.*100; % Convert to Pa/m
Exp_H2O{:,10} = 0.001002; % Add K for H2O
Exp_H2O{:,11} = 1; % Add n for H2O


% Assign variable names
Exp_H2O.Properties.VariableNames = {'RPM',...
    'Date',...
    'Fluid',...
    'MassFlowRate',...
    'Density',...
    'Usl_p',...
    'Usl_ae',...
    'dpdl_p',...
    'dpdl_ae',...
    'K',...
    'n'};

Exp_PAC.Properties.VariableNames = {'RPM',...
    'Date',...
    'Fluid',...
    'K',...
    'n',...
    'MassFlowRate',...
    'Density',...
    'Usl_p',...
    'Usl_ae',...
    'dpdl_p',...
    'dpdl_ae'};

% Reorder 
Exp_H2O = Exp_H2O(:,{'Date',...
    'Fluid',...
    'MassFlowRate',...
    'RPM',...
    'Density',...
    'K',...
    'n',...
    'dpdl_p',...
    'dpdl_ae',...
    'Usl_p',...
    'Usl_ae'});

% Reorder 
Exp_PAC = Exp_PAC(:,{'Date',...
    'Fluid',...
    'MassFlowRate',...
    'RPM',...
    'Density',...
    'K',...
    'n',...
    'dpdl_p',...
    'dpdl_ae',...
    'Usl_p',...
    'Usl_ae'});

% Merge H2O and PAC tables
Exp = [Exp_H2O;Exp_PAC];

% Remove rows with zero-like mass flow
Exp(Exp.MassFlowRate<0.01,:) = [];

% Convert date
Exp.Date = datenum(Exp.Date); %,'mm-dd-yy');
Exp.Date = datestr(Exp.Date,'yyyy-mm-dd');


%% Compute derived variables 

Exp.Usl_p = SuperficialVelocity (Exp.MassFlowRate, Exp.Density, do, di, 3);
Exp.Usl_ae = SuperficialVelocity (Exp.MassFlowRate, Exp.Density, do, di, 2);
Exp.ReG_p = GeneralizedReynoldsNumber ( Exp.Density, Exp.Usl_p, do, di, 3, Exp.n, Exp.K );
Exp.ReG_a = GeneralizedReynoldsNumber ( Exp.Density, Exp.Usl_p, do, di, 2, Exp.n, Exp.K );
Exp.f_p = FanningFrictionFactor_Exp ( Exp.Density, Exp.Usl_p, do, di, 3, Exp.dpdl_p );
% Exp.f_a = FanningFrictionFactor_Exp ( Exp.Density, Exp.Usl_a, do, di, 2, Exp.dpdl_a );
Exp.f_ae = FanningFrictionFactor_Exp ( Exp.Density, Exp.Usl_ae, do, di, 2, Exp.dpdl_ae );


%% Compute analytical/empirical solutions
Exp.f_p_comp = FanningFrictionFactor_Ref ( Exp.ReG_p, Exp.Fluid, 3 );
% Exp.fana_a = FanningFrictionFactor_Ref ( Exp.ReG_a, Exp.Fluid, 2 );
% Exp.fana_ae = FanningFrictionFactor_Ref  ( Exp.ReG_a, Exp.Fluid, 2 );

Exp.dpdl_p_comp = PressureGradient ( Exp.f_p_comp, Exp.Density, Exp.Usl_p, do, di, 3);
% Exp.dpdlana_a = PressureGradient ( Exp.f_a, Exp.Density, Exp.Usl_ae, do, di, 2); % Usl_a = Usl_ae
% Exp.dpdlana_ae = PressureGradient ( Exp.f_ae, Exp.Density, Exp.Usl_ae, do, di, 2);




%% Compute delta between exp. and analytical/empirical solutions
Exp.delta_dpdl_p = Exp.dpdl_p - Exp.dpdl_p_comp;
Exp.delta_f_p = Exp.f_p - Exp.f_p_comp;

% Normalized with experimental data
Exp.delta_dpdl_p_normalized = Exp.delta_dpdl_p./Exp.dpdl_p;
Exp.delta_f_p_normalized = Exp.delta_f_p./Exp.f_p;

% Normalized with analytical/empirical solution
Exp.delta_dpdl_p_normalized = Exp.delta_dpdl_p./Exp.dpdl_p_comp;
Exp.delta_f_p_normalized = Exp.delta_f_p./Exp.f_p_comp;

% Ratio of experimental and computed pressure gradient
Exp.dpdl_p_ratio = Exp.dpdl_p./Exp.dpdl_p_comp;


%% Assign units
Exp.Properties.VariableUnits = {'tbd',...
    '-',...
    'kg/s',...
    '1/min',...
    'kg/m³',...
    'Pa.s^n',...
    '-',...
    'Pa/m',...
    'Pa/m',...
    'm/s',...
    'm/s',...
    '-',...
    '-',...
    '-',...
    '-',...
    '-',...
    '-',...
    '-',...
    '-',...
    '-',...
    '-',...
    '-'};

%% Clear workspace
clear Exp_H2O Exp_PAC