function [fitresult, gof] = CreatePLFit(SR, Tau)
%CreatePLFit(NESR,TAUW)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : NeSR
%      Y Output: TauW
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-Sep-2016 15:35:09


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( SR, Tau );

% Set up fittype and options.
ft = fittype( 'power1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.338774183690378 0.631723549043171];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'TauW vs. NeSR', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel NeSR
% ylabel TauW
% grid on


