function [ ] = FormatSubplots ( subplotname )
%FormatSubplots Summary of this function goes here
%   Detailed explanation goes here


%% General settings
grid('on');
set(gca,...
    'box','on',...
    'FontSize',18);

%% Specific settings


switch subplotname
    case {'p_dpdl_mdot' 'a_dpdl_mdot'}
        xlabel('Mass flow rate [kg/s]');
        ylabel('Pressure gradient [Pa/m]');
        set(gca,...
            'xlim', [0 2]);
            if strcmp(subplotname,'p_dpdl_mdot')
                set(gca,'ylim', [0 1250]);
            else
                set(gca,'ylim', [0 4250]);
            end
        
    case {'p_f_Usl' 'a_f_Usl'}
        xlabel('Bulk Velocity V [m/s]');
        ylabel('Fanning friction factor [-]');
        set(gca,...
            'XScale','log',...
            'YScale','log',...
            'XTick', [0.1 0.5 1]);
        if strcmp(subplotname,'p_f_Usl')
            set(gca,...
            'xlim', [0.1 1],...
            'ylim', [5e-3 6e-1]);
        else
            set(gca,...
                'xlim', [0.1 1.6],...
                'ylim', [5e-3 7e-1]);
        end
  
    case {'p_f_ReG' 'a_f_ReG'}
        xlabel('Generalized Reynolds number [-]');
        ylabel('Fanning friction factor [-]');
        set(gca,...
            'XScale','log',...
            'YScale','log',...
            'xlim', [4e1 4e4],...
            'XTick', [10 100 1000 10000 ],...
            'ylim', [5e-3 7e-1]);
          
    case {'PipeVisco'}
        xlabel('Newtonian shear rate 8V/D [1/s]');
        ylabel('Shear stress at the wall [N/m²]');
        set(gca,...
            'XScale','log',...
            'YScale','log',...
            'xlim', [1e1 4e2],...
            'ylim', [3e-1 2e1]);
            
    case {'Rheometry'}
        xlabel('Shear rate [1/s]');
        ylabel('Apparent viscosity [Pa.s]');
        set(gca,...
            'XScale','log',...
            'YScale','log',...
            'ylim', [5e-3 3e-1]);


end

end

%  
%     'XScale','log',...
%     'YScale','log',...
%     'xlim', [10 100000],...
%     'ylim', [0.001 1],...
%     'XTick', [1e-2 1e-1 1e-0 1e1 1e2 1e3],...
%     'YTick', [1e-2 2e-2 3e-2 4e-2 5e-2 1e-1 2e-1 3e-1 4e-1 5e-1 1e-0 2e-0],...


