function [fitresult, gof] = createPolynomialFit(x, y, data)
%CREATEFIT(RPM,Q_F,ECCENTRICITY)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : rpm
%      Y Input : Q_f
%      Z Output: eccentricity
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 13-Sep-2018 10:38:21


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( x, y, data );

% Set up fittype and options.
ft = fittype( 'poly22' );

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, [xData, yData], zData );
% legend( h, 'untitled fit 1', 'eccentricity vs. rpm, Q_f', 'Location', 'NorthEast' );
% % Label axes
% xlabel rpm
% ylabel Q_f
% zlabel eccentricity
% grid on
% view( -19.9, 1.2 );


