function [fitresult, gof] = createFits1(Up_SR, AV_M, Up_AV_M, Down_SR, Down_AV_M)
%CREATEFITS1(UP_SR,AV_M,UP_AV_M,DOWN_SR,DOWN_AV_M)
%  Create fits.
%
%  Data for 'Total_mean' fit:
%      X Input : Up_SR
%      Y Output: AV_M
%  Data for 'Upward_sweep' fit:
%      X Input : Up_SR
%      Y Output: Up_AV_M
%  Data for 'Downward_sweep' fit:
%      X Input : Down_SR
%      Y Output: Down_AV_M
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 31-May-2016 08:59:02

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 3, 1 );
gof = struct( 'sse', cell( 3, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'Total_mean'.
[xData, yData] = prepareCurveData( Up_SR, AV_M );

% Set up fittype and options.
ft = fittype( 'ny_inf+(ny_0-ny_inf)/(1+(k*x)^n)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0];
opts.StartPoint = [0.913375856139019 0.6324 0.25 0.01];
opts.Upper = [10 1 1 1];

% Fit model to data.
[fitresult{1}, gof(1)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Total_mean' );
h = plot( fitresult{1}, xData, yData );
legend( h, 'AV_M vs. Up_SR', 'Total_mean', 'Location', 'NorthEast' );
% Label axes
xlabel Up_SR
ylabel AV_M
grid on

%% Fit: 'Upward_sweep'.
[xData, yData] = prepareCurveData( Up_SR, Up_AV_M );

% Set up fittype and options.
ft = fittype( 'ny_inf+(ny_0-ny_inf)/(1+(k*x)^n)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0];
opts.StartPoint = [0.485375648722841 0.8002804688888 0.141886338627215 0.421761282626275];
opts.Upper = [10 1 1 1];

% Fit model to data.
[fitresult{2}, gof(2)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Upward_sweep' );
h = plot( fitresult{2}, xData, yData );
legend( h, 'Up_AV_M vs. Up_SR', 'Upward_sweep', 'Location', 'NorthEast' );
% Label axes
xlabel Up_SR
ylabel Up_AV_M
grid on

%% Fit: 'Downward_sweep'.
[xData, yData] = prepareCurveData( Down_SR, Down_AV_M );

% Set up fittype and options.
ft = fittype( 'ny_inf+(ny_0-ny_inf)/(1+(k*x)^n)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0];
opts.StartPoint = [0.933993247757551 0.678735154857773 0.757740130578333 0.743132468124916];
opts.Upper = [10 1 1 1];

% Fit model to data.
[fitresult{3}, gof(3)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Downward_sweep' );
h = plot( fitresult{3}, xData, yData );
legend( h, 'Down_AV_M vs. Down_SR', 'Downward_sweep', 'Location', 'NorthEast' );
% Label axes
xlabel Down_SR
ylabel Down_AV_M
grid on


