% Schiller Nauman vs Stokes
    Re_p = logspace(-5,5);
    figure
    hold on
    plot(Re_p,24./Re_p)
    plot(Re_p,(24./Re_p).*(1+0.15.*(Re_p.^0.687)))

    set(gca,...
        'XScale','log',...
        'YScale','log',...
        'xlim', [1e-2 1e1],...
        'ylim', [1e0 1e3],...
        'box','on');