function [fitresult, gof] = createFit(Time_extract, Viscosity_extract, type)
%CREATEFIT(TIME_EXTRACT,VISCOSITY_EXTRACT)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : Time_extract
%      Y Output: Viscosity_extract
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Aug-2016 12:08:12


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( Time_extract, Viscosity_extract );

% Set up fittype and options.
if strcmp(type,'increasing')
    ft = fittype( 'ny_0+(ny_inf-ny_0)*(1-exp((-1/tau)*x))', 'independent', 'x', 'dependent', 'y' );
else
    ft = fittype( 'ny_inf+(ny_0-ny_inf)*(1-exp((-1/tau)*x))', 'independent', 'x', 'dependent', 'y' ); % Original: ny_inf+(ny_0-ny_inf)*(1-exp((-1/tau)*x))
end

opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0];
opts.StartPoint = [0.157613081677548 0.970592781760616 0.957166948242946];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'Viscosity_extract vs. Time_extract', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel Time_extract
% ylabel Viscosity_extract
% grid on


