function [y,vel_x] = importExportedQuantities(filename, ID, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [NODE,X,Y,Z,YPLUS,PROD_K,RE_TURB,SDR,TDR,TKE,VISCOSITY_TURB,VEL_Y,VEL_X,VEL_MAG]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [NODE,X,Y,Z,YPLUS,PROD_K,RE_TURB,SDR,TDR,TKE,VISCOSITY_TURB,VEL_Y,VEL_X,VEL_MAG]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [node,x,y,z,yplus,prod_k,Re_turb,sdr,tdr,tke,viscosity_turb,vel_y,vel_x,vel_mag] = importfile('p_newtonian-scaled_dpdx=0.001.txt',1, 61);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/07/12 14:00:49



% filename =fullpath
% ID =cases.ID{aa}



%% Initialize variables.
delimiter = ' ';
if nargin<=3
    startRow = 1;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,6,7,8,9,10,11,12,13,14]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Allocate imported array to column variable names
if (strcmp(ID,'180525_1') || strcmp(ID,'180525_2') || strcmp(ID,'180526_3') || strcmp(ID,'180615_1') || strcmp(ID,'180526_1'))
    node = cell2mat(raw(:, 1));
    x = cell2mat(raw(:, 2));
    y = cell2mat(raw(:, 3));
    z = cell2mat(raw(:, 4));
    tdr = cell2mat(raw(:, 5));
    tke = cell2mat(raw(:, 6));
    viscosity_turb = cell2mat(raw(:, 7));
    vel_y = cell2mat(raw(:, 8));
    vel_x = cell2mat(raw(:, 9));
    vel_mag = cell2mat(raw(:, 10));
else
    node = cell2mat(raw(:, 1));
    x = cell2mat(raw(:, 2));
    y = cell2mat(raw(:, 3));
    z = cell2mat(raw(:, 4));
    yplus = cell2mat(raw(:, 5));
    prod_k = cell2mat(raw(:, 6));
    Re_turb = cell2mat(raw(:, 7));
    sdr = cell2mat(raw(:, 8));
    tdr = cell2mat(raw(:, 9));
    tke = cell2mat(raw(:, 10));
    viscosity_turb = cell2mat(raw(:, 11));
    vel_y = cell2mat(raw(:, 12));
    vel_x = cell2mat(raw(:, 13));
    vel_mag = cell2mat(raw(:, 14));
end




%% Transpose so that data can be filled into table
y=y';
vel_x=vel_x';
