%% Clean-up
clear all;
close all;
clc;


col_PAC8 = [0,0,0]; %[0,0,1]; 
col_PAC4 = [0,80,158]/255; %[0,0.5,1]; 
col_PAC2 = [144, 73, 45]/255; %[0,1,1]; 

addpath 'E:\OneDrive_NTNU\SWwd\MATLAB\Generic\m-files';

% Load time scales
load FC_Cross_PAC2.mat;
load FC_Cross_PAC4.mat;
load Timescales_FC_PAC2.mat;
load Timescales_FC_PAC4.mat;
load Timescales_FS.mat;
load Timescales_3ITT.mat;
load Timescales_3ITT_Large.mat;
load Timescales_FNSD_PAC2.mat;
load Timescales_FNSD_PAC4.mat;


%% Figure
fig1 = figure('color','w','Units','centimeters','Position',[1 1 12 8.45]); % DIN A5 
hold on;

xlabel('$\dot\gamma$ [1/s]','FontSize',10,'Interpreter','latex');
ylabel('$\lambda_i$ [s]','FontSize',10,'Interpreter','latex');
grid('off');

xmin = 0.08;
xmax = 1400;

ax1 = gca;
set(ax1,...
    'XScale','log',...
    'YScale','log',...
    'xlim', [xmin xmax],...
    'ylim', [1e-2 1e3],...
    'box','on');
ax1.Layer = 'top';



% Cross-based
test = plot(ShearRate, lambda_Cr_PAC2 .* ones(1,length(ShearRate)),'-','LineWidth',1,'Color',col_PAC2);
text(min(ShearRate),lambda_Cr_PAC2,'Cross',...
    'HorizontalAlignment','left',...
    'VerticalAlignment','bottom',...
    'FontSize',10,...
    'FontWeight','normal',...
    'Color',col_PAC2);


plot(ShearRate, lambda_Cr_PAC4 .* ones(1,length(ShearRate)),'-','LineWidth',1,'Color',col_PAC4);
text(min(ShearRate),lambda_Cr_PAC4,'Cross',...
    'HorizontalAlignment','left',...
    'VerticalAlignment','bottom',...
    'FontSize',10,...
    'FontWeight','normal',...
    'Color',col_PAC4);


% Carreau-based
plot(ShearRate, lambda_Ca_PAC2 .* ones(1,length(ShearRate)),'-','LineWidth',1,'Color',col_PAC2);
text(1e1,lambda_Ca_PAC2, 'Carreau',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'FontSize',10,...
    'FontWeight','normal',...
    'Color',col_PAC2);

plot(ShearRate, lambda_Ca_PAC4 .* ones(1,length(ShearRate)),'-','LineWidth',1,'Color',col_PAC4);
text(max(ShearRate),lambda_Ca_PAC4, 'Carreau',...
    'HorizontalAlignment','right',...
    'VerticalAlignment','bottom',...
    'FontSize',10,...
    'FontWeight','normal',...
    'Color',col_PAC4);


% PL-based - High shear rates
plot(ShearRate(ShearRate>=48.3), lambda_PL_highSR_PAC2 .* ones(1,length(ShearRate(ShearRate>=48.3))),'-','LineWidth',1,'Color',col_PAC2);
text(max(ShearRate),lambda_PL_highSR_PAC2,'Power-law',...
    'HorizontalAlignment','right',...
    'VerticalAlignment','top',...
    'FontSize',10,...
    'FontWeight','normal',...
    'Color',col_PAC2);

plot(ShearRate(ShearRate>=48.3), lambda_PL_highSR_PAC4 .* ones(1,length(ShearRate(ShearRate>=48.3))),'-','LineWidth',1,'Color',col_PAC4);
text(max(ShearRate),lambda_PL_highSR_PAC4,'Power-law',...
    'HorizontalAlignment','right',...
    'VerticalAlignment','bottom',...
    'FontSize',10,...
    'FontWeight','normal',...
    'Color',col_PAC4);



% 3ITT-based - Low shear rate intervall
plot(0.1,lambda_3ITT_100_50_PAC2,'o','Color',col_PAC2,'MarkerFaceColor',col_PAC2);
text(0.11,lambda_3ITT_100_50_PAC2,'3ITT 100-50-500',...
    'HorizontalAlignment','left',...
    'VerticalAlignment','bottom',...
    'FontSize',10,...
    'FontWeight','normal',...
    'Color',col_PAC2);

plot(0.1,lambda_3ITT_100_50_PAC4,'o','Color',col_PAC4,'MarkerFaceColor',col_PAC4);
text(0.11,lambda_3ITT_100_50_PAC4,'3ITT 100-50-500',...
    'HorizontalAlignment','left',...
    'VerticalAlignment','top',...
    'FontSize',10,...
    'FontWeight','normal',...
    'Color',col_PAC4);

plot(0.1,lambda_3ITT_300_600_PAC2,'o','Color',col_PAC2,'MarkerFaceColor',col_PAC2);
text(0.11,lambda_3ITT_300_600_PAC2,'3ITT 300-600-500',...
    'HorizontalAlignment','left',...
    'VerticalAlignment','top',...
    'FontSize',10,...
    'FontWeight','normal',...
    'Color',col_PAC2);

plot(0.1,67.6,'o','Color',col_PAC2,'MarkerFaceColor',col_PAC2);
text(0.11,67.6,'3ITT 300-600-500',...
    'HorizontalAlignment','left',...
    'VerticalAlignment','top',...
    'FontSize',10,...
    'FontWeight','normal',...
    'Color',col_PAC2);

plot(0.1,lambda_3ITT_300_600_PAC4,'o','Color',col_PAC4,'MarkerFaceColor',col_PAC4);
text(0.11,lambda_3ITT_300_600_PAC4,'3ITT 300-600-500',...
    'HorizontalAlignment','left',...
    'VerticalAlignment','bottom',...
    'FontSize',10,...
    'FontWeight','normal',...
    'Color',col_PAC4);

plot(0.1,lambda_3ITT_300_600_PAC4_LowShearRate,'o','Color',col_PAC4,'MarkerFaceColor',col_PAC4);
text(0.11,lambda_3ITT_300_600_PAC4_LowShearRate,'3ITT 300-600-500',...
    'HorizontalAlignment','left',...
    'VerticalAlignment','middle',...
    'FontSize',10,...
    'FontWeight','normal',...
    'Color',col_PAC4);

plot(0.1,lambda_3ITT_100_50_PAC4_LowShearRate,'o','Color',col_PAC4,'MarkerFaceColor',col_PAC4);
text(0.11,lambda_3ITT_100_50_PAC4_LowShearRate,'3ITT 100-50-500',...
    'HorizontalAlignment','left',...
    'VerticalAlignment','bottom',...
    'FontSize',10,...
    'FontWeight','normal',...
    'Color',col_PAC4);


% 3ITT-based - High shear rate intervall
plot(1200,lambda_3ITT_300_600_PAC4_HighShearRate,'o','Color',col_PAC4,'MarkerFaceColor',col_PAC4);
text(1150,lambda_3ITT_300_600_PAC4_HighShearRate,'3ITT 300-600-500',...
    'HorizontalAlignment','right',...
    'VerticalAlignment','middle',...
    'FontSize',10,...
    'FontWeight','normal',...
    'Color',col_PAC4);


% Maxwell-based
plot(AngularFrequency_PAC2*0.2, MaxwellRelaxationTime_PAC2,'-o','Color',col_PAC2,'MarkerFaceColor','none');
text(3e-1,1e-1,'Maxwell',...
    'HorizontalAlignment','right',...
    'VerticalAlignment','middle',...
    'Rotation',0,...
    'FontSize',10,...
    'FontWeight','normal',...
    'Color',col_PAC2);


% % Import UiS data for entire range of shear rate
% parentpath = cd(cd('..'));
% path2 = [parentpath '\FS\'];
% [~, ~, raw] = xlsread([path2 'FS.xlsx'],'UiS','A3:I23');
% 
% % Create output variable
% data = reshape([raw{:}],size(raw));
% 
% % Allocate imported array to column variable names
% AngularFrequency_PAC4 = data(:,2);
% MaxwellRelaxationTime_PAC4 = data(:,8);
% 
% % Clear temporary variables
% clearvars data raw;

plot(AngularFrequency_PAC4*0.2, MaxwellRelaxationTime_PAC4,'-o','Color',col_PAC4,'MarkerFaceColor','none');
text(1e-0,1.4e-1,'Maxwell',...
    'HorizontalAlignment','left',...
    'VerticalAlignment','middle',...
    'Rotation',0,...
    'FontSize',10,...
    'FontWeight','normal',...
    'Color',col_PAC4);


% FNSD-based (RS : Recoverable Shear)
g(10)=plot(ShearRate, lambda_FNSD_PAC2,'--','LineWidth',1,'Color',col_PAC2);
text(2e1,max(lambda_FNSD_PAC2),'Recoverable shear',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','bottom',...
    'FontSize',10,...
    'FontWeight','normal',...
    'Color',col_PAC2);

g(10)=plot(ShearRate, lambda_FNSD_PAC4,'--','LineWidth',1,'Color',col_PAC4);
text(1e0,lambda_FNSD_PAC4(end),'Recoverable shear',...
    'HorizontalAlignment','left',...
    'VerticalAlignment','top',...
    'FontSize',10,...
    'FontWeight','normal',...
    'Color',col_PAC4);


annotation('arrow',[0.5 0.5], [0.5 0.94])
text(6e0,1e0,'Thixotropic','HorizontalAlignment','center','VerticalAlignment','middle','Rotation',0,'FontSize',14,'FontWeight','bold','Color','k'); %'interpreter','latex'
annotation('arrow',[0.77 0.77], [0.4 0.16])
text(1e2,7e-1,'Viscoelastic','HorizontalAlignment','center','VerticalAlignment','middle','Rotation',0,'FontSize',14,'FontWeight','bold','Color','k'); %'interpreter','latex'




% h_legend = legend(g(1:10),...
%     'Power-law',...
%     'Power-law (High shear rates)',...
%     'Power-law (Low shear rates)',...
%     '3ITT 100-50-X ($\dot \gamma = 0.1$ 1/s, Lab1 \& Lab2)',...
%     '3ITT 300-600-X ($\dot \gamma = 0.1$ 1/s, Lab1 \& Lab2)',...
%     '3ITT 300-600-X ($\dot \gamma = 0.1$ 1/s, Lab1 \& Lab2)',...
%     '3ITT 300-600-X ($\dot \gamma = 1200$ 1/s, Lab1 \& Lab2)',...
%     'Cross',...
%     'Maxwell',...
%     'First Normal Stress Coefficient');
% 
% set(h_legend,...
%     'Location','north',...
%     'Interpreter','Latex',...
%     'FontSize',24);




% Expand Axes to Fill Figure (--> Minimum white space)
ax = gca;
outerpos = ax.OuterPosition;
ti = ax.TightInset;
factor_hor = 0.01;
factor_ver = 0.01;
left = outerpos(1) + ti(1) + factor_hor;
bottom = outerpos(2) + ti(2) + factor_ver;
ax_width = outerpos(3) - ti(1) - ti(3) - 2*factor_hor;
ax_height = outerpos(4) - ti(2) - ti(4) - 2*factor_ver;
ax.Position = [left bottom ax_width ax_height];

% Specify Figure Size and Page Size
set(fig1,'PaperPositionMode','auto') %set paper pos for printing
fig_pos = fig1.PaperPosition;
fig1.PaperSize = [fig_pos(3) fig_pos(4)];

% Save Figure to File Format
path1 = '\\home.ansatt.ntnu.no\alexabus\Documents\AdWell\8 - Publications & Conferences\2016-05 - Rheological properties of PAC\Paper - V3 - Applied Rheology - Timescale Overview\Resub2\Figures\';
fig_name = 'TimeScales';
print(fig1,[path1 fig_name],'-dpdf','-bestfit');  % '-dpng' '-depsc' 'jpeg' '-depsc2' '-depsc'
print(fig1,[path1 fig_name],'-depsc');  % '-dpng' '-depsc' 'jpeg' '-depsc2' '-depsc'
print(fig1,[path1 fig_name],'-dmeta');  % '-dpng' '-depsc' 'jpeg'
print(fig1,[path1 num2str(11)],'-dpng','-r600')
% saveas(fig, [path fig_name],'png') % save figure
% save2pdf([path fig_nam],fig,600) % requires m-file