function [fitresult, gof] = createFit1(x, y)
%CREATEFIT1(ANGULARFREQUENCY,FIRSTNORMALSTRESSDIFF)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : AngularFrequency
%      Y Output: FirstNormalStressDiff
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Apr-2017 19:48:26


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'K*x^n', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0];
opts.Robust = 'LAR';
opts.StartPoint = [0.1712 0.706046088019609];
opts.Upper = [1 3];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Fit' );
h = plot( fitresult, xData, yData );
legend( h, 'Data', 'Fit', 'Location', 'NorthEast' );
% Label axes
xlabel 'x'
ylabel 'y'
grid on
set(gca,...
    'XScale','log',...
    'YScale','log');

