function [fitresult, gof] = createFit(ShearRate, Fluid, Model, Lower, StartPoint, Upper)
%CREATEFIT(SHEARRATE,FLUID1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : ShearRate
%      Y Output: Fluid1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 09-Feb-2016 18:03:30


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( ShearRate, Fluid );

% Set up fittype and options.
ft = fittype( Model, 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = Lower;
opts.StartPoint = StartPoint;
opts.Upper = Upper;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'Fluid1 vs. ShearRate', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel ShearRate
% ylabel Fluid1
% grid on


