%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: M:\Documents\SW_working_directories\MATLAB\ParaSpace\ParaSpace.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/06/07 08:57:14

%% Import the data
[~, ~, raw] = xlsread('C:\Users\alexabus\IEPT1325_Local\Data\SWwd\MATLAB\ParaSpace\ParaSpace.xlsx','Sheet1','A3:P10');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {0}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Hole = data(:,1);
Pipe = data(:,2);
Length = data(:,3);
Inclination = data(:,4);
Eccentricity_R = data(:,5);
Eccentricity_Theta = data(:,6);
Flow = data(:,7);
YP = data(:,8);
PV = data(:,9);
FluidDens = data(:,10);
PartDia = data(:,11);
PartDens = data(:,12);
Porosity = data(:,13);
BotHolTemp = data(:,14);
rpm = data(:,15);
ROP = data(:,16);

%% Clear temporary variables
clearvars data raw R;

