%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook:
%    C:\Users\alexanderb\Documents\MATLAB\Exploration_DrillingMud.xls
%    Worksheet: wellbore_mud
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2015/11/04 14:51:03

clc;
clear all;
close all;

%% Import the data
[~, ~, raw0_0] = xlsread('C:\Users\alexabus\IEPT1325_Local\Data\SW_working_directories\MATLAB\Rheology\NPD PV and YP data\Exploration_DrillingMud.xls','wellbore_mud','B1:E31383');
[~, ~, raw0_1] = xlsread('C:\Users\alexabus\IEPT1325_Local\Data\SW_working_directories\MATLAB\Rheology\NPD PV and YP data\Exploration_DrillingMud.xls','wellbore_mud','H1:H31383');
raw = [raw0_0,raw0_1];
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Clear temporary variables
clearvars raw raw0_0 raw0_1 R;