function [fitresult, gof] = FitYvelocity(t, y, ft)
%FitYvelocity(T,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 06-Sep-2017 08:35:42


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( t, y );

% Set up fittype and options.
% ft = fittype( 'poly2' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
if strcmp(ft,'poly4')
    opts.Lower = [-Inf -Inf -Inf -Inf -Inf];
    opts.Upper = [Inf Inf Inf Inf Inf];
else
    opts.Lower = [-Inf -Inf -Inf -Inf];
    opts.Upper = [Inf Inf Inf Inf];
end

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'y vs. t', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel t
% ylabel y
% grid on




