close all;
clear all;
clc;

addpath(genpath('C:\Users\alexabus\OneDrive_NTNU\SWwd\MATLAB\Generic'));
addpath([pwd '\utilities']);
fig_path = 'M:\Documents\AdWell\8 - Publications & Conferences\2018-xx - Turbulence\Figures\';

% Read data
 load('turbulencedata.mat');
 
 
 % Turbulence models: ID, LineStyle, LineWidth, Marker, MarkerSize
turbmodels = [unique(cases.Models), {'none'; 'none'; '-'; '--'; ':'; '-.'}, {1; 1; 1; 1; 1; 1}, {'s'; 's'; 'o'; 'o'; 'o'; 'o'}, {10; 10; 2; 2; 2; 2}];

% Fluids: ID, Color
fluids = sortrows([unique(cases.Fluid), {'green'; 'cyan'; 'blue'; 'red'}, {4; 1; 2; 3}], 3);

% Geometry
geo = unique(cases.Geometry); geo = flip(geo);

% Create sorting index of fluids for plot purposes in case table
looplength = size(fluids); looplength = looplength(1);
for aa=1:height(cases)
    for bb=1:looplength
        if strcmp(cases.Fluid(aa),fluids(bb,1))
            cases.Fluidsortindex{aa} = (fluids{bb,3});
        end
    end
end

 % Exclude data from all plots

    % Remove k-omega SST low-Re
    toDelete = (strcmp(cases.Turbulence,'k-omega SST') & strcmp(cases.LowRe,'Low Re'));
    cases(toDelete,:) = [];
    turbmodels = turbmodels(1:5,:);

    % Remove n=0.75 pipe case 
    toDelete = (strcmp(cases.Geometry,'Pipe') & strcmp(cases.Fluid,'PL') & cases.n_PL_scaled==0.75);
    cases(toDelete,:) = [];

 
 aa=1

     % Create dimensional plots dpdx = f(mdot) for pipe and annulus
    fig_handle(1+2*aa-1) = CreateFigure(['Pressure gradient vs. mass flow rate (' geo{aa} ')'],'Mass flow rate dm/dt [kg/s]', 'Pressure gradient dp/dx [Pa/m]', {'lin' 'lin'}, 'DINA5');
    
 
 % Create non-dimensional plots f = f(Re_MR) for pipe and annulus
    fig_handle(1+2*aa) = CreateFigure(['friction factor vs. Metzner-Reed Reynolds number (' geo{aa} ')'],'Metzner-Reed Reynolds number Re_M_R [-]', 'Fanning friction factor f [-]', {'log' 'log'}, 'DINA5'); % 'PowerPoint'
    
    % Plot friction factor correlations on f-Re_MR plot
    Correlations;
    
    % Create table subset for pipe or annulus    
    cases2print = cases(strcmp(cases.Geometry,geo(aa)) & strcmp(cases.u_x_spec,'x'),:);
    
    % Further filtering of cases2print
    if strcmp(geo(aa),'Annulus')
        cases2print = cases2print(cases2print.e==0 & contains(cases2print.Description,'rpm=0')==1,:);
    else

    end
    
    % Sort rows
    cases2print = sortrows(cases2print,{'Fluidsortindex','Turbulence','LowRe','nNlowReMod'});
    
    % Expand legendentries (created in "Correlations"
    legendentrieslength = size(legendentries); legendentrieslength = legendentrieslength(1);
    legendentries = [legendentries; cell(height(cases2print),1)];
    

    
    bb=3

        % Get index of current cases for respective plot formatting cell arrays
        idx_turb = find(strcmp(turbmodels,cases2print.Models(bb)));
        idx_fluid = find(strcmp(fluids,cases2print.Fluid(bb)));
          % dpdx vs. mdot
        figure(fig_handle(1+2*aa-1));
        plot(cases2print.mdot{bb,1},cases2print.dpdx{bb,1},...
            'LineStyle',turbmodels{idx_turb,2},...
            'Color',fluids{idx_fluid,2},...
            'LineWidth',turbmodels{idx_turb,3},...
            'Marker',turbmodels{idx_turb,4},...
            'MarkerSize',turbmodels{idx_turb,5},...
            'MarkerEdgeColor',fluids{idx_fluid,2},...
            'MarkerFaceColor','none');
        
        % f vs. Re_MR
        figure(fig_handle(1+2*aa));
        plot(cases2print.Re_MR{bb,1},cases2print.f{bb,1},...
            'LineStyle',turbmodels{idx_turb,2},...
            'Color',fluids{idx_fluid,2},...
            'LineWidth',turbmodels{idx_turb,3},...
            'Marker',turbmodels{idx_turb,4},...
            'MarkerSize',turbmodels{idx_turb,5},...
            'MarkerEdgeColor',fluids{idx_fluid,2},...
            'MarkerFaceColor','none');
        
            
    bb=4;
            % dpdx vs. mdot
        figure(fig_handle(1+2*aa-1));
        plot(cases2print.mdot{bb,1},cases2print.dpdx{bb,1},...
            'LineStyle',turbmodels{idx_turb,2},...
            'Color',fluids{idx_fluid,2},...
            'LineWidth',turbmodels{idx_turb,3},...
            'Marker','o',...
            'MarkerSize',turbmodels{idx_turb,5},...
            'MarkerEdgeColor',fluids{idx_fluid,2},...
            'MarkerFaceColor','none');
        
        % f vs. Re_MR
        figure(fig_handle(1+2*aa));
            plot(cases2print.Re_MR{bb,1},cases2print.f{bb,1},...
            'LineStyle',turbmodels{idx_turb,2},...
            'Color',fluids{idx_fluid,2},...
            'LineWidth',turbmodels{idx_turb,3},...
            'Marker','o',...
            'MarkerSize',turbmodels{idx_turb,5},...
            'MarkerEdgeColor',fluids{idx_fluid,2},...
            'MarkerFaceColor','none');
        
            
    bb=7

        % Get index of current cases for respective plot formatting cell arrays
        idx_turb = find(strcmp(turbmodels,cases2print.Models(bb)));
        idx_fluid = find(strcmp(fluids,cases2print.Fluid(bb)));
          % dpdx vs. mdot
        figure(fig_handle(1+2*aa-1));
        plot(cases2print.mdot{bb,1},cases2print.dpdx{bb,1},...
            'LineStyle',turbmodels{idx_turb,2},...
            'Color',fluids{idx_fluid,2},...
            'LineWidth',turbmodels{idx_turb,3},...
            'Marker',turbmodels{idx_turb,4},...
            'MarkerSize',turbmodels{idx_turb,5},...
            'MarkerEdgeColor',fluids{idx_fluid,2},...
            'MarkerFaceColor','none');
        
        % f vs. Re_MR
        figure(fig_handle(1+2*aa));
        plot(cases2print.Re_MR{bb,1},cases2print.f{bb,1},...
            'LineStyle',turbmodels{idx_turb,2},...
            'Color',fluids{idx_fluid,2},...
            'LineWidth',turbmodels{idx_turb,3},...
            'Marker',turbmodels{idx_turb,4},...
            'MarkerSize',turbmodels{idx_turb,5},...
            'MarkerEdgeColor',fluids{idx_fluid,2},...
            'MarkerFaceColor','none');
        
            
    bb=8;
            % dpdx vs. mdot
        figure(fig_handle(1+2*aa-1));
        plot(cases2print.mdot{bb,1},cases2print.dpdx{bb,1},...
            'LineStyle',turbmodels{idx_turb,2},...
            'Color',fluids{idx_fluid,2},...
            'LineWidth',turbmodels{idx_turb,3},...
            'Marker','o',...
            'MarkerSize',turbmodels{idx_turb,5},...
            'MarkerEdgeColor',fluids{idx_fluid,2},...
            'MarkerFaceColor','none');
        
        % f vs. Re_MR
        figure(fig_handle(1+2*aa));
            plot(cases2print.Re_MR{bb,1},cases2print.f{bb,1},...
            'LineStyle',turbmodels{idx_turb,2},...
            'Color',fluids{idx_fluid,2},...
            'LineWidth',turbmodels{idx_turb,3},...
            'Marker','o',...
            'MarkerSize',turbmodels{idx_turb,5},...
            'MarkerEdgeColor',fluids{idx_fluid,2},...
            'MarkerFaceColor','none');